### ISSUE TITLE
在编译bootimgtools时候缺少很多依赖

### ISSUE THREAD

**Issue by thouger** [bmax121/AndroidKernelPatch#1]
`
cd imgtools
mkdir build; cd build
cmake ..
make
`
在最后make的时候出现很多出错，我尝试修改了一下,比如
`
android error: ‘strlen’ was not declared in this scope
`
我将`#include <string>`改成`#include <cstring>`，
`error: ‘sDIR’ does not name a type; did you mean ‘DIR’?`，我改成#include <dirent.h>，但是问题太多了，要改很多东西
[make.log](https://github.com/bmax121/AndroidKernelPatch/files/12404616/make.log)

**Comment by thouger** [comment]
我修改了一下午，还是改不动了，太多错误了
[1.log](https://github.com/bmax121/AndroidKernelPatch/files/12407435/1.log)

**Comment by bmax121** [comment]
文档很久前写的，刚刚更新，bootimgtools 代码是从 magisk 改过来的，是为了解包 boot.img，暂时没有做过太多的适配。直接用app吧，或者用 magisk 解包，
